# templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: finetune
  labels:
    app: finetune
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: finetune
  template:
    metadata:
      labels:
        app: finetune
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag  }}"
          ports:
           - containerPort: {{ .Values.containerPort}}
